### ISSUE TITLE
Inner block doesn't expanded

### ISSUE THREAD

**Issue by dmytrodubinin** [freder/logseq-plugin-jump-to-block#1]
In your video and description I see: "It lets you fuzzy search the 'table of contents' of the current page and scroll to the selected block. If the any parent blocks of the selected block are collapsed, they will be expanded."
But when I try to open inner block, nothing happened. Here is the demo:
[Screencast from 2023-03-23 09-17-30.webm](https://user-images.githubusercontent.com/8066458/227131568-e09e086c-43c8-4824-845c-fe76ffc9ea30.webm)

OS: Arch Linux
Logseq 0.8.18, app restarted after plugin installed

**Comment by freder** [comment]
- do you get any errors in the console?
- would you be able to share the page with me for testing/debugging?

**Comment by dmytrodubinin** [comment]
I have this problem in every page, no errors in console.
Here is the demo with disable all other extensions 
[Screencast from 2023-03-23 14-38-14.webm](https://user-images.githubusercontent.com/8066458/227206708-59ed2300-3975-4d65-9fb1-2469c0d29cf1.webm)

The file from video:
[bug page.md](https://github.com/freder/logseq-plugin-jump-to-block/files/11050876/bug.page.md)

**Comment by dmytrodubinin** [comment]
The problem is still here in v1.1.2

**Comment by freder** [comment]
unfortunately I cannot reproduce this. expanding works for me on macos and linux.

**Comment by dmytrodubinin** [comment]
The plugin is currently not working at all.
[Screencast from 2023-03-27 10-11-46.webm](https://user-images.githubusercontent.com/8066458/227867686-372645b6-bc2d-4722-a9c8-ae14386918f6.webm)

Plugin 1.2.0
No console errors
OS: Linux

**Comment by dmytrodubinin** [comment]
I tested on several Linux machines (Fedora and Arch) and this functionality did not work anywhere. I showed a demo that the problem exists. Perhaps you still haven't tested on Linux? On which distribution did you check which kind of package you used?

**Comment by freder** [comment]
not sure why I wasn't able to reproduce this issue before, but I can now. – reopening.

**Comment by freder** [comment]
should be fixed now. please test with [v1.5.2](https://github.com/freder/logseq-plugin-jump-to-block/releases/tag/v1.5.2)

**Comment by dmytrodubinin** [comment]
Yes, Thank You!
