### ISSUE TITLE
Feature request: When activating the search box, add a configuration item for whether the first one is selected by default

### ISSUE THREAD

**Issue by MountainEthics** [freder/logseq-plugin-jump-to-block#12]
When I open this plugin and the search box appears, is it possible to not have the first one selected by default. This default check to scroll to the first block has always caused me a lot of frustration.

**Comment by freder** [comment]
I agree, that would be a better experience.

**Comment by freder** [comment]
will be included in the next release

![image](https://user-images.githubusercontent.com/724844/233772924-863e15bb-d6b8-4a0f-bedd-c2694e108ede.png)

**Comment by MountainEthics** [comment]
Thank you for your response and for your plugin work!

**Comment by freder** [comment]
https://github.com/freder/logseq-plugin-jump-to-block/releases/tag/v1.4.0
