### ISSUE TITLE
[Feature Request] Only Jump to Headings

### ISSUE THREAD

**Issue by likecreep** [freder/logseq-plugin-jump-to-block#18]
Hi, Thanks for your wonderful work.

As logseq doesn't show a table of contents for each page in the sidebar. So is there a way to limit this plugin only show blocks that are headings so that I can use it to jump to headings?

**Comment by freder** [comment]
good idea!

for [v1.5.0](https://github.com/freder/logseq-plugin-jump-to-block/releases/tag/v1.5.0) I went with the easiest solution: adding a setting that lets you pick a mode.

![image](https://user-images.githubusercontent.com/724844/234106400-8897c49d-2ea6-485a-aac6-e573de98aaad.png)

in the future it could be interesting to work with different prefixes, [like vscode does](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)

another option might be to have separate shortcuts for different modes.
