### ISSUE TITLE
Plugin popup window doesn't follow logseq theme 

### ISSUE THREAD

**Issue by dmytrodubinin** [freder/logseq-plugin-jump-to-block#2]
It would be nice if the plugin used the same theme as the program itself
At the moment it uses the standard white theme, regardless of the Logseq settings.
![Screenshot from 2023-03-23 09-24-55](https://user-images.githubusercontent.com/8066458/227132353-ae7cb36f-1e97-4db8-a2fc-e0f1fe8c1f81.png)

**Comment by freder** [comment]
good point. – I need to figure out how a plugin get ahold of the theme colors.

ultimately I would [want to use the built-in command palette](https://discuss.logseq.com/t/let-plugins-create-custom-command-palettes/16129) and not have to deal with things like that, but until then...

**Comment by freder** [comment]
https://github.com/freder/logseq-plugin-jump-to-block/releases/tag/v1.1.0 now uses the theme colors

**Comment by dmytrodubinin** [comment]
Can't check, because plugin crash app again.

**Comment by freder** [comment]
had to revert, since accessing the theme colors does not work when the plugin is installed via the marketplace.

**Comment by freder** [comment]
`v1.2.0` should finally work
