### ISSUE TITLE
Bug Report: In certain situation, heading would be ignored.

### ISSUE THREAD

**Issue by likecreep** [freder/logseq-plugin-jump-to-block#22]
When two headings are adjacent to each other with no content separator in between, the last heading is ignored.

For example: 
```txt
## HEAD1
    ### SubHead1
    ### SubHead2
## HEAD2
## HEAD3
```
The result would be:
HEAD1
---SubHead2
HEAD3

As you can see, subHead1 and HEAD2 are ignored.

**Comment by freder** [comment]
like that?

<img width="896" alt="image" src="https://github.com/freder/logseq-plugin-jump-to-block/assets/724844/c4839339-d629-43ca-a543-60af86c06460">

could you share the file in question here?

**Comment by freder** [comment]
thanks for clarifying. — should be fixed in the latest version.
