### ISSUE TITLE
Running inside indent block returns to the root of the page

### ISSUE THREAD

**Issue by dmytrodubinin** [freder/logseq-plugin-jump-to-block#8]
If you call the plugin inside a nested block, then the user is automatically returned to the root page
Demo:
[Screencast from 2023-03-28 10-02-09.webm](https://user-images.githubusercontent.com/8066458/228155733-82367d99-4157-4998-9b4d-282a9c2fbea2.webm)

ps. as a before, plugin on Linux doesn't work without console errors...

**Comment by freder** [comment]
as mentioned [here](https://github.com/freder/logseq-plugin-jump-to-block/issues/3#issuecomment-1483098597) that's the best I can do for now I'm afraid... until I find a way to resolve #4
